import { Metadata } from "next";
import "./style.css";
export const metadata: Metadata = {
  title: {
    default: "first next js project",
    template: "%s|product",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header className="bg-red-500">header</header>
        {children}
        <footer>footer</footer>
      </body>
    </html>
  );
}
